### ISSUE TITLE
请移除flutter平台版本限制

### ISSUE THREAD

**Issue by duhualong** [jpush/jpush-flutter-plugin#249]
jpush_flutter：^0.6.3版本 
请在 pubspec.yaml移除 platform: ^2.0.0；我在自己的pubspec.yaml 同时引入path_provider: ^2.0.1和jpush_flutter：^0.6.3会提示
Because path_provider >=2.0.0 depends on path_provider_platform_interface ^2.0.0 which depends on platform ^3.0.0, path_provider >=2.0.0 requires platform ^3.0.0.
And because jpush_flutter 0.6.3 depends on platform ^2.0.0 and no versions of jpush_flutter match >0.6.3 <0.7.0, path_provider >=2.0.0 is incompatible with jpush_flutter ^0.6.3.
So, because ** depends on both jpush_flutter ^0.6.3 and path_provider ^2.0.1, version solving failed.

**Comment by wenchaosong** [comment]
+1

flutter 升级 2.0 报错

**Comment by panzhoutao** [comment]
+1

**Comment by 371726787** [comment]
+1
Because every version of jpush_flutter from git depends on platform ^2.0.0 and path_provider_platform_interface >=2.0.0 depends on platform ^3.0.0, jpush_flutter from git is incompatible with path_provider_platform_interface >=2.0.0.

And because shared_preferences >=2.0.0 depends on shared_preferences_windows ^2.0.0 which depends on path_provider_platform_interface ^2.0.0, jpush_flutter from git is incompatible with shared_preferences >=2.0.0.

**Comment by panzhoutao** [comment]
我是把代码拉到本地，把限制去掉解决

**Comment by gaoqian526** [comment]
+1

**Comment by jeromekai** [comment]
希望处理一下2.0 兼容问题

**Comment by mofan20** [comment]
+1
Because shared_preferences >=2.0.0 depends on shared_preferences_windows ^2.0.0 and no versions of shared_preferences_windows match >2.0.0 <3.0.0, shared_preferences >=2.0.0 requires shared_preferences_windows 2.0.0.
