### ISSUE TITLE
upgrade needed

### ISSUE THREAD

**Issue by jinjilynn** [jpush/jpush-flutter-plugin#251]
jpush_flutter ^0.6.3, version solving failed  jpush_flutter ^0.6.3 requires platform ^2.0.0.

**Comment by 49756916** [comment]
The current Dart SDK version is 2.10.4.                                 
                                                                        
Because jpush_flutter >=0.6.3 depends on platform >=3.0.0-nullsafety.4 which requires SDK version >=2.12.0-0 <3.0.0, jpush_flutter >=0.6.3 is forbidden.
So, because workmeet_flutter depends on jpush_flutter 0.6.3, version solving failed.
